# Generated by Django 4.2 on 2023-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=25, max_length=100),
            preserve_default=False,
        ),
    ]
