# Generated by Django 4.2 on 2023-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0002_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_name', models.CharField(max_length=255)),
                ('cop_pin_code', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
