# Generated by Django 4.2 on 2023-04-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0005_rename_country_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='add_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
