# Generated by Django 4.2 on 2023-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0006_address_add_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Banking',
        ),
        migrations.AddField(
            model_name='city',
            name='city_pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
