# Generated by Django 4.2 on 2023-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0007_rename_company_banking_city_city_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_name', models.CharField(max_length=255)),
                ('cop_pin_code', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RenameField(
            model_name='banking',
            old_name='cop_name',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='banking',
            name='cop_pin_code',
        ),
        migrations.AddField(
            model_name='banking',
            name='city_pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
