# Generated by Django 4.2 on 2023-04-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0008_user_delete_city_rename_cop_name_banking_city_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Banking',
        ),
    ]
