# Generated by Django 4.2 on 2023-04-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0009_delete_address_delete_banking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
