# Generated by Django 4.2 on 2023-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0012_rename_user_city_rename_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='indore', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='india', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='madhya_pradesh', max_length=255),
            preserve_default=False,
        ),
    ]
