# Generated by Django 4.2 on 2023-04-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0013_city_city_name_country_country_name_state_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='st_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_name',
        ),
    ]
