# Generated by Django 4.2 on 2023-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0014_rename_state_name_state_st_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='indore', max_length=255),
            preserve_default=False,
        ),
    ]
