# Generated by Django 4.2 on 2023-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0016_rename_city_name_city_ci_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Coun',
        ),
    ]
