# Generated by Django 4.2 on 2023-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0017_rename_country_coun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='st_name',
            new_name='state_of_name',
        ),
    ]
