# Generated by Django 4.2 on 2023-04-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0018_rename_st_name_state_state_of_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_of_name',
            new_name='state_name',
        ),
    ]
