# Generated by Django 4.2 on 2023-04-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0019_rename_state_of_name_state_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='ci_name',
            new_name='city_name',
        ),
    ]
