# Generated by Django 4.2 on 2023-04-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0021_remove_city_city_name_coun_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coun',
            old_name='country_name',
            new_name='coun_name',
        ),
    ]
