# Generated by Django 4.2 on 2023-04-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0022_rename_country_name_coun_coun_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coun',
            old_name='coun_name',
            new_name='country_name',
        ),
    ]
