# Generated by Django 4.2 on 2023-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0025_rename_coun_country_remove_city_city_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='st_name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
