# Generated by Django 4.2 on 2023-04-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0026_rename_state_name_state_st_name_city_city_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Coun',
        ),
    ]
