# Generated by Django 4.2 on 2023-04-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0027_rename_country_coun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coun',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='st_name',
            new_name='state_name',
        ),
    ]
