# Generated by Django 4.2 on 2023-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0029_rename_city_city_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='st_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_name',
        ),
        migrations.AddField(
            model_name='city_model',
            name='city_pin_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
