# Generated by Django 4.2 on 2023-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0030_user_rename_state_name_state_st_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='state',
            name='st_name',
        ),
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
