# Generated by Django 4.2 on 2023-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0031_delete_user_remove_state_st_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='st_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
