# Generated by Django 4.2 on 2023-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0033_rename_state_state_model_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='state_model',
            old_name='st_name',
            new_name='state_name',
        ),
        migrations.AddField(
            model_name='city_model',
            name='city_pin_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
