# Generated by Django 4.2 on 2023-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0034_user_rename_st_name_state_model_state_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State_Model',
            new_name='State',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='city_model',
            name='city_pin_code',
        ),
        migrations.AddField(
            model_name='country',
            name='country_pin_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
