# Generated by Django 4.2 on 2023-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0035_rename_state_model_state_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_model',
            name='city_pin_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
