# Generated by Django 4.2 on 2023-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0037_remove_state_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
